[project]
name = "text2playlist"
version = "1.0.0"
description = "A set of tools for handling music links and metadata."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.54.0",
    "watchdog>=6.0.0",
]
